apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  # This is the config file for prometheus
  # What is global scrape_interval: the metrics gets refreshed every 15s
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flask-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['34.42.228.136:5000']
# The job is to monitor prometheus itself and our flask-app
# flask-app IP should be given and 5000 port
# - targets: ['34.42.228.136:5000']  - VM IP [IP_ADDRESS]